import { ROUTES } from './routes.js';

/**
 * Public and Customer facing navigation links.
 * Each object supports a detailed schema for flexible rendering in Navbar, Footer, and Mobile views.
 */
export const NAV_LINKS = [
  {
    label: 'Home',
    href: ROUTES.HOME,
    icon: 'HomeIcon',
    requiresAuth: false,
    roles: null,
    showInNavbar: true,
    showInFooter: true,
    showInMobileMenu: true,
    isComingSoon: false,
  },
  {
    label: 'Shop',
    href: ROUTES.PRODUCTS,
    icon: 'ShopIcon',
    requiresAuth: false,
    roles: null,
    showInNavbar: true,
    showInFooter: true,
    showInMobileMenu: true,
    isComingSoon: false,
  },
  {
    label: 'Categories',
    href: ROUTES.CATEGORIES,
    icon: 'CategoryIcon',
    requiresAuth: false,
    roles: null,
    showInNavbar: true,
    showInFooter: true,
    showInMobileMenu: true,
    isComingSoon: false,
  },
  {
    label: 'Offers',
    href: ROUTES.OFFERS,
    icon: 'OfferIcon',
    requiresAuth: false,
    roles: null,
    showInNavbar: true,
    showInFooter: true,
    showInMobileMenu: true,
    isComingSoon: false,
  },
  {
    label: 'About',
    href: ROUTES.ABOUT,
    icon: 'InfoIcon',
    requiresAuth: false,
    roles: null,
    showInNavbar: true,
    showInFooter: true,
    showInMobileMenu: true,
    isComingSoon: false,
  },
  {
    label: 'Contact',
    href: ROUTES.CONTACT,
    icon: 'ContactIcon',
    requiresAuth: false,
    roles: null,
    showInNavbar: true,
    showInFooter: true,
    showInMobileMenu: true,
    isComingSoon: false,
  },
  {
    label: 'Cart',
    href: ROUTES.CART,
    icon: 'CartIcon',
    requiresAuth: false,
    roles: null,
    showInNavbar: false,
    showInFooter: false,
    showInMobileMenu: true,
    isComingSoon: false,
  },
  {
    label: 'Wishlist',
    href: ROUTES.WISHLIST,
    icon: 'HeartIcon',
    requiresAuth: true,
    roles: null,
    showInNavbar: false,
    showInFooter: false,
    showInMobileMenu: true,
    isComingSoon: true, // Mark as future placeholder
  },
  {
    label: 'My Orders',
    href: ROUTES.ORDERS,
    icon: 'OrderIcon',
    requiresAuth: true,
    roles: null,
    showInNavbar: false,
    showInFooter: true,
    showInMobileMenu: true,
    isComingSoon: false,
  },
];

/**
 * Admin Panel navigation links.
 * Prepared for nested navigation layouts.
 */
export const ADMIN_NAV_LINKS = [
  {
    label: 'Dashboard',
    href: ROUTES.ADMIN_DASHBOARD,
    icon: 'DashboardIcon',
    requiresAuth: true,
    roles: ['admin', 'superadmin'],
    showInNavbar: false,
    showInFooter: false,
    showInMobileMenu: false,
    isComingSoon: false,
    children: [],
  },
  {
    label: 'Products',
    href: ROUTES.ADMIN_PRODUCTS,
    icon: 'ProductIcon',
    requiresAuth: true,
    roles: ['admin', 'superadmin'],
    showInNavbar: false,
    showInFooter: false,
    showInMobileMenu: false,
    isComingSoon: false,
    children: [],
  },
  {
    label: 'Categories',
    href: ROUTES.ADMIN_CATEGORIES,
    icon: 'CategoryIcon',
    requiresAuth: true,
    roles: ['admin', 'superadmin'],
    showInNavbar: false,
    showInFooter: false,
    showInMobileMenu: false,
    isComingSoon: false,
    children: [],
  },
  {
    label: 'Offers',
    href: ROUTES.ADMIN_OFFERS,
    icon: 'OfferIcon',
    requiresAuth: true,
    roles: ['admin', 'superadmin'],
    showInNavbar: false,
    showInFooter: false,
    showInMobileMenu: false,
    isComingSoon: false,
    children: [],
  },
  {
    label: 'Inquiries',
    href: ROUTES.ADMIN_CONTACTS,
    icon: 'ContactIcon',
    requiresAuth: true,
    roles: ['admin', 'superadmin'],
    showInNavbar: false,
    showInFooter: false,
    showInMobileMenu: false,
    isComingSoon: false,
    children: [],
  },
  {
    label: 'Subscribers',
    href: ROUTES.ADMIN_SUBSCRIBERS,
    icon: 'NewsletterIcon',
    requiresAuth: true,
    roles: ['admin', 'superadmin'],
    showInNavbar: false,
    showInFooter: false,
    showInMobileMenu: false,
    isComingSoon: false,
    children: [],
  },
  {
    label: 'Settings',
    href: ROUTES.ADMIN_SETTINGS,
    icon: 'SettingsIcon',
    requiresAuth: true,
    roles: ['admin', 'superadmin'],
    showInNavbar: false,
    showInFooter: false,
    showInMobileMenu: false,
    isComingSoon: false,
    children: [],
  },
];
