/**
 * Centralized configurable Home Featured Products settings.
 * Allows managing products mock database arrays (names, prices, tags, stock limits)
 * without editing React markup, matching backend schemas.
 */

export const PRODUCTS_CONFIG = [
  {
    id: 'prod-banarasi-sherwani',
    name: 'Royal Gold Banarasi Sherwani',
    slug: 'royal-gold-banarasi-sherwani',
    image: '/images/product-1.png',
    price: 18999,
    originalPrice: 24999,
    discountPercentage: 24,
    category: 'Wedding Sherwanis',
    featured: true,
    rating: 4.9,
    reviewCount: 156,
    isNew: false,
    isBestSeller: true,
    stock: 12,
  },
  {
    id: 'prod-silk-kurta-wine',
    name: 'Classic Silk Kurta - Wine Red',
    slug: 'classic-silk-kurta-wine-red',
    image: '/images/product-2.png',
    price: 3499,
    originalPrice: 4999,
    discountPercentage: 30,
    category: 'Designer Kurtas',
    featured: true,
    rating: 4.7,
    reviewCount: 98,
    isNew: true,
    isBestSeller: false,
    stock: 25,
  },
  {
    id: 'prod-nehru-jacket-mint',
    name: 'Handcrafted Pastel Mint Nehru Jacket',
    slug: 'handcrafted-pastel-mint-nehru-jacket',
    image: '/images/product-3.png',
    price: 4500,
    originalPrice: 5999,
    discountPercentage: 25,
    category: 'Nehru Jackets',
    featured: true,
    rating: 4.8,
    reviewCount: 74,
    isNew: true,
    isBestSeller: true,
    stock: 8,
  },
  {
    id: 'prod-indowestern-suit',
    name: 'Emerald Festive Indo-Western Fusion Suit',
    slug: 'emerald-festive-indowestern-fusion-suit',
    image: '/images/product-4.png',
    price: 12999,
    originalPrice: 16999,
    discountPercentage: 23,
    category: 'Indo-Western & Suits',
    featured: true,
    rating: 4.6,
    reviewCount: 42,
    isNew: false,
    isBestSeller: false,
    stock: 15,
  },
];
